output "public_ip" {
  description = "Elastic IP attached to the EC2 instance"
  value       = aws_eip.instance.public_ip
}

output "public_http_url" {
  description = "HTTP endpoint on the instance"
  value       = "http://${aws_eip.instance.public_ip}"
}

output "instance_id" {
  value = aws_instance.web.id
}

output "keypair_saved_to" {
  value       = var.generate_keypair ? var.private_key_path : "(not generated by Terraform)"
  description = "Path of the generated private key (if enabled)."
}
